/*INSERT INTO subject(code, name, create_date, modify_date) VALUES ('D001', '내과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D002', '소아청소년과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D003', '신경과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D004', '정신건강의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D005', '피부과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D006', '외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D007', '흉부외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D008', '정형외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D009', '신경외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D010', '성형외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D011', '산부인과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D012', '안과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D013', '이비인후과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D014', '비뇨기과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D016', '재활의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D017', '마취통증의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D018', '영상의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D019', '치료방사선과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D020', '임상병리과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D021', '해부병리과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D022', '가정의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D023', '핵의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D024', '응급의학과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D026', '치과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                 ('D034', '구강악안면외과', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 */