name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_SECRET
          script_stop: true
          script: |
            cd /home/ubuntu/careQ
            rm -rf src/main/resources/application-secret.yml
            git pull origin main
            echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 8083 || true 
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &